name: flutter_20250209
description: 김대순 차민희 모바일 청첩장 입니다.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # state management, dependency injection, route router_management
  get: ^4.6.6

  url_launcher: ^6.2.4
  card_swiper: ^3.0.1
  youtube_player_iframe: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# dependency_overrides:
#   web: ^0.4.0

flutter:
  uses-material-design: true

  fonts:
    - family: defaultFont
      fonts:
        - asset: assets/fonts/default_font_light.otf
          weight: 300
        - asset: assets/fonts/default_font_bold.otf
          weight: 500

    - family: gothicFont
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.ttf
    - family: cormorantGaramondFont
      fonts:
        - asset: assets/fonts/CormorantGaramond-Medium.ttf

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/daesun_minhee/
